# Generated by Django 4.1 on 2022-11-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qings', '0003_poet_quote_delete_poets_delete_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='video/%y')),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='poet',
            name='image',
            field=models.ImageField(upload_to='static/%y'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='image',
            field=models.ImageField(upload_to='static/%y'),
        ),
    ]
